
/*CREACION DE TABLAS PRIMARY KEY*/
/*TABLA DIRECCION_SUCURSAL*/
/* SE ELIGIO EL NOMBRE DIRECCION SUCURSAL PARA ESTA TABLA POR QUE ALMACENA LAS DIRECCIONES DE CADA SUCURSAL. 
 * CON ID_DIRECCION_SUCURUSAL, CALLE, COLONIA, NUMERO_EXTERIOR, NUMERO_INTERIOR, CP, ESTADO Y CIUDAD.
 * 
 *ID_DIRECCION_SUCURSAL: SE ELIGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO QUE REPRESENTA LAS DIRECCIONES DE LAS SUCURSALES, ES LLAVE
 *PRIMARIA EN LA TABLA QUE PERMITE IDENTIFICARLAS DE UNA MANERA RAPIDA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * CALLE: SE ELIGIO VARCHAR2(100) POR QUE ES TIPO TEXTO Y SU LONGITUD ES DE ASTA 100 CARACTERES, SE CALCULA QUE CON ESO ES SUFICIENTE
 * PARA EL NOMBRE DE UNA CALLE, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * COLONIA: SE ELIGIO VARCHAR2(100) POR QUE ES TIPO TEXTO Y SU LONGITUD ES DE ASTA 100 CARACTERES, SE CALCULA QUE CON ESO ES SUFICIENTE
 * PARA EL NOMBRE DE UNA COLONIA NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * NUMERO_EXTERIOR: SE ELIGIO NUMBER, POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * NUMERO_INTERIOR: SE ELIGIO NUMBER, POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * CP: SE ELEGIO NUMBER, POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA
 * 
 * ESTADO: SE ELIGIO VARCHAR2(50) POR QUE ES TIPO TEXTO Y SU LONGITUD ES DE ASTA 50 CARACTERES, SE CALCULA QUE CON ESO ES SUFICIENTE
 * PARA EL NOMBRE DE UN ESTADO DE LA REPUBLICA MEXICANA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * CIUDAD: SE ELIGIO VARCHAR2(100) POR QUE ES TIPO TEXTO Y SU LONGITUD ES DE ASTA 100 CARACTERES, SE CALCULA QUE CON ESO ES SUFICIENTE
 * PARA EL NOMBRE DE UNA CIUDAD, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 */
CREATE TABLE C##PROYECTO1.DIRECCION_SUCURSAL(
ID_DIRECCION_SUCURSAL NUMBER PRIMARY KEY NOT NULL,
CALLE VARCHAR2(100) NOT NULL,
COLONIA VARCHAR2(100) NOT NULL,
NUMERO_EXTERIOR NUMBER NOT NULL,
NUMERO_INTERIOR NUMBER NOT NULL,
CP NUMBER NOT NULL,
ESTADO VARCHAR2(50) NOT NULL,
CIUDAD VARCHAR2(100) NOT NULL
);

/*TABLA TELEFONO_SUCURSAL*/
/*SE ELIGIO EL NOMBRE TELEFONO SUCURSAL PARA ESTA TABLA POR QUE ALMACENA LOS NUMEROS TELEFONICOS DE CADA SUCURSAL. 
 * CON ID_TELEFONO_SUCURUSAL Y TELEFONO.
 * 
 *ID_TELEFONO_SUCURSAL: SE ELIGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO QUE REPRESENTA CADA TELEFONO DE LAS SUCURSALES, ES LLAVE
 *PRIMARIA EN LA TABLA QUE PERMITE IDENTIFICARLAS DE UNA MANERA RAPIDA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 *TELEFONO: SE ELIGIO NUMBER(10) POR QUE ES TIPO NUMERICO Y SU LONGITUD ES DE ASTA 10 CARACTERES, ES LA LONGITUD ESTANDAR PARA UN NUMERO DE
 *DE TELEFONO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 *
 */
CREATE TABLE C##PROYECTO1.TELEFONO_SUCURSAL(
ID_TELEFONO_SUCURSAL NUMBER PRIMARY KEY NOT NULL,
TELEFONO NUMBER(10) NOT NULL
);

/*TABLA IMPUESTO*/
/* SE ELIGIO EL NOMBRE DE IMPUESTOS PARA ESTA TABLA POR QUE ALMACENA LOS IMPUESTOS QUE SE ESTAN GENERANDO
 * CON ID_IMPUESTO, NOMBRE Y PORCENTAJE */
/*
 * ID_IMPUESTO: SE ELIGIO NUMBER POR QUE NECESITA UN INDENTIFICADOR UNICO QUE REPRESENTA CADA IMPUESTO, ES LLAVE PRIMARIA EN LA TABLA
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA
 * 
 * NOMBRE: SE ELEGIO VARCHAR2(100) POR QUE ES TIPO TEXTO CON LONGITUD DE ASTA 100 CARACTERES, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA
 * 
 * PORCENTAJE: SE ELIGIO NUMBER, POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 */
CREATE TABLE C##PROYECTO1.IMPUESTO(
ID_IMPUESTO NUMBER PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(100) NOT NULL,
PORCENTAJE FLOAT NOT NULL
);

/*TABLA DIRECCION_PROVEEDOR*/
/*SE ELEGIO EL NOMBRE DE DIRECCION_PROVEEDOR PARA ESTA TABLA POR QUE ALMACENA LA INFORMACION DE LAS DIREECIONES DE LOS PROVEEDORES QUE
 * SUMINISTRAN LOS PRODUCTOS.
 * CON ID_DIRRECION_PROVEEDOR, CALLE, COLONIA, NUMERO_EXTERIOR, NUMERO_INTERIOR, CP, ESTADO, CIUDAD
 * 
 * ID_DIRECCION_PROVEEDOR:SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA LA DIRECCION DE CADA PROVEDOR,
 * LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * CALLE: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * COLONIA: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * NUMERO_EXTERIOR: SE ELIGIO NUMBER POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * NUMERO_INTERIOR: SE ELIGIO NUMBER POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * CP: SE ELIGIO NUMBER POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * ESTADO: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES, SE CALCULA QUE ES LA LONGITUD
 * PARA EL NOMBRE DE UN ESTADO DE LA REPUBLICA MEXICANA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * CIUDAD: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES, SE CALCULA QUE ES LA LONGITUD
 * PARA EL NOMBRE DE UNA CIUDAD, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 */
CREATE TABLE C##PROYECTO1.DIRECCION_PROVEEDOR(
ID_DIRECCION_PROVEEDOR NUMBER PRIMARY KEY NOT NULL,
CALLE VARCHAR2(100) NOT NULL,
COLONIA VARCHAR2(100) NOT NULL,
NUMERO_EXTERIOR NUMBER NOT NULL,
NUMERO_INTERIOR NUMBER NOT NULL,
CP NUMBER NOT NULL,
ESTADO VARCHAR2(100) NOT NULL,
CIUDAD VARCHAR2(100) NOT NULL
);

/*TABLA TELEFONO_PROVEEDOR*/
/*SE ELIGIO EL NOMBRE TELEFONO_PROVEEDOR PARA ESTA TABLA POR QUE ALMACENA LA INFORMACION DE LOS NUMEROS TELEFONICOS DE LOS PROVEEDORES
 * CON ID_TELEFONO_PROVEEDOR Y TELEFONO
 * 
 * ID_TELEFONO_PROVEEDOR: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO EL NUMERO TELEFONICO DE CADA PROVEDOR,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * TELEFONO: SE ELIGIO NUMBER POR QUE ES DE TIPO NUMERICO, CON LONGITUD DE 10 CARACTERES, ES EL TAMAÑO ESTANDAR DE LOS NUMEROS
 * TELEFONICOS, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 */
CREATE TABLE C##PROYECTO1.TELEFONO_PROVEEDOR(
ID_TELEFONO_PROVEEDOR NUMBER PRIMARY KEY NOT NULL,
TELEFONO NUMBER(10) NOT NULL
);

/*TABLA CATEGORIA*/
/*SE ELIGIO EL NOMBRE DE CATEGORIA PARA ESTA TABLA POR QUE GUARDA LA INFORMACION DE LAS DIFERENTES CATEGORIAS DE LOS PRODUCTOS EN VENTA
 * CON ID_CATEGORIA, NOMBRE Y DESCRIPCION.
 * 
 * ID_CATEGORIA: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA CADA CATEGORIA,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * NOMBRE: SE ELIGIO VARCHAR2(100) POR QUE ES TIPO TEXTO CON UNA LONGITUD DE 100 CARACTERES.
 * 
 * DESCRIPCION: SE ELIGIO VARCHAR2(200) POR QUE ES TIPO TEXTO CON UNA LONGITUD DE 200 CARACTERES PARA UNA ALPLIA DESCRIPCION
 */
CREATE TABLE C##PROYECTO1.CATEGORIA(
ID_CATEGORIA NUMBER PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(100) NOT NULL,
DESCRIPCION VARCHAR2(200) NOT NULL
);

/*TABLA TELEFONO_EMPLEADO*/
/*SE ELIGIO EL NOMBRE DE TELEFONO_EMPLEADO PARA ESTA TABLA POR QUE GUARDA LOS NUMEROS TELEFONICOS DE CADA EMPLEADO
 *CON ID_TELEFONO_EMPLEADO Y TELEFONO
 *
 * ID_TELEFONO_EMPLEADO: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA CADA NUMERO TELEFONICO DE EMPLEADO,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * TELEFONO: SE ELIGIO NUMBER POR QUE ES DE TIPO NUMERICO, CON LONGITUD DE 10 CARACTERES, ES EL TAMAÑO ESTANDAR DE LOS NUMEROS
 * TELEFONICOS, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 */
CREATE TABLE C##PROYECTO1.TELEFONO_EMPLEADO(
ID_TELEFONO_EMPLEADO NUMBER PRIMARY KEY NOT NULL,
TELEFONO NUMBER(10) NOT NULL
);

/*TABLA DIRECCION_EMPLEADO*/
/*SE ELIGIO EL NOMBRE DE DIRECCION_EMPLEADO PARA ESTA TABLA POR QUE GUARDA LA INFORMACION DE LAS DIRECCIONES DE CADA EMPLEADO
 * CON ID_DIRECCION_EMPLEADO, CALLE, COLONIA, NUMERO_INTERIOR, NUMERO_EXTERIOR, CP, ESTADO, CIUDAD
 * 
 * ID_DIRECCION_EMPLEADO: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA LA DIRECCION DE CADA EMPLEADO,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * CALLE: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * COLONIA: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * NUMERO_IXTERIOR: SE ELIGIO NUMBER POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * NUMERO_EXTERIOR: SE ELIGIO NUMBER POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * CP: SE ELIGIO NUMBER POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * ESTADO: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES, SE CALCULA QUE ES LA LONGITUD
 * PARA EL NOMBRE DE UN ESTADO DE LA REPUBLICA MEXICANA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * CIUDAD: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES, SE CALCULA QUE ES LA LONGITUD
 * PARA EL NOMBRE DE UNA CIUDAD, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 */
CREATE TABLE C##PROYECTO1.DIRECCION_EMPLEADO(
ID_DIRECCION_EMPLEADO NUMBER PRIMARY KEY NOT NULL,
CALLE VARCHAR2(100) NOT NULL,
COLONIA VARCHAR2(100) NOT NULL,
NUMERO_INTERIOR NUMBER NOT NULL,
NUMERO_EXTERIOR NUMBER NOT NULL,
CP NUMBER NOT NULL,
ESTADO VARCHAR2(100) NOT NULL,
CIUDAD VARCHAR2(100) NOT NULL
);

/*TABLA ROL*/
/*SE ELIGIO EL NOMBRE DE ROL PARA ESTA TABLA POR QUE GUARDA EL ROL QUE DESEMPEÑA CADA EMPLEADO 
 * CON ID_ROL Y NOMBRE
 * 
 * ID_ROL: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA EL ROL DE CADA EMPLEADO,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * NOMBRE: SE ELIGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 */
CREATE TABLE C##PROYECTO1.ROL(
ID_ROL NUMBER PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(100) NOT NULL
);

/*TABLA METODO_DE_PAGO*/
/*SE ELIGIO EL NOMBRE DE METODO_DE_PAGO PARA ESTA TABLA POR QUE GUARDA LA INFORMACION DE COMO FUE EL METODO DE PAGO 
 * CON ID_METODO_DE_PAGO, NOMBRE Y DESCRIPCION
 * 
 * ID_METODO_DE_PAGO: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA CADA METODO DE PAGO REALIZADO,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * NOMBRE: SE ELIGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * DESCRIPCION: SE ELIGIO VARCHAR2(200) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 200 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 */
CREATE TABLE C##PROYECTO1.METODO_DE_PAGO(
ID_METODO_DE_PAGO NUMBER PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(100) NOT NULL,
DESCRIPCION VARCHAR2(200) NOT NULL
);

/*TABLA DIRECCION_CLIENTE*/
/*SE ELIGIO EL NOMBRE DE DIRECCION_CLIENTE PARA ESTA TABLA POR QUE GUARDA LAS DIRECCIONES DE LOS CLIENTES QUE COMPRAN 
 * CON ID_DIRECCION_CLIENTE, CALLE, COLONIA, NUMERO_INTERIOR, NUMERO_EXTERIOR, CP, ESTADO Y CIUDAD.
 * 
 * ID_DIRECCION_CLIENTE: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA LA DIRECCION DE CADA CLIENTE,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * CALLE: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * COLONIA: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * NUMERO_IXTERIOR: SE ELIGIO NUMBER POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * NUMERO_EXTERIOR: SE ELIGIO NUMBER POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * CP: SE ELIGIO NUMBER POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * ESTADO: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES, SE CALCULA QUE ES LA LONGITUD
 * PARA EL NOMBRE DE UN ESTADO DE LA REPUBLICA MEXICANA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * CIUDAD: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES, SE CALCULA QUE ES LA LONGITUD
 * PARA EL NOMBRE DE UNA CIUDAD, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 */
CREATE TABLE C##PROYECTO1.DIRECCION_CLIENTE(
ID_DIRECCION_CLIENTE NUMBER PRIMARY KEY NOT NULL,
CALLE VARCHAR2(100) NOT NULL,
COLONIA VARCHAR2(100) NOT NULL,
NUMERO_INTERIOR NUMBER NOT NULL,
NUMERO_EXTERIOR NUMBER NOT NULL,
CP NUMBER NOT NULL,
ESTADO VARCHAR2(100) NOT NULL,
CIUDAD VARCHAR2(100) NOT NULL
);

/*TABLA CLIENTE*/
/*SE ELIGIO EL NOMBRE DE TELEFONO_CLIENTE PARA ESTA TABLA POR QUE GUARDA LOS NUMEROS TELEFONICOS DE CADA CLIENTE
 *CON ID_TELEFONO_CLIENTE Y TELEFONO
 *
 * ID_TELEFONO_CLIENTE: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA CADA NUMERO TELEFONICO DE CADA CLIENTE,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * TELEFONO: SE ELIGIO NUMBER POR QUE ES DE TIPO NUMERICO, CON LONGITUD DE 10 CARACTERES, ES EL TAMAÑO ESTANDAR DE LOS NUMEROS
 * TELEFONICOS, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 */
CREATE TABLE C##PROYECTO1.TELEFONO_CLIENTE(
ID_TELEFONO_CLIENTE NUMBER PRIMARY KEY NOT NULL,
TELEFONO NUMBER(10) NOT NULL
);

/*TABLAS CON LLAVES FORANEAS*/
/*TABLA SUCURSAL*/
 /* SE ELIGIO EL NOMBRE SUCURSAL PARA ESTA TABLA POR QUE GUARDA LA INFORMACION DE CADA SOCURSAL
 * CON ID_SUCURSAL, NOMBRE, FK_DIRECCION_SUCURSAL Y FK_TELEFONO_SUCURSAL
 * 
 * ID_SUCURSAL: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA CADA SUCURSAL,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * NOMBRE: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * FK_DIRECCION_SUCURSAL: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA DIRECCION_SUCURSAL
 * 
 * FK_TELEFONO_SUCURSAL: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA TELEFONO_SUCURSAL
 */
CREATE TABLE C##PROYECTO1.SUCURSAL(
ID_SUCURSAL NUMBER PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(100) NOT NULL,
FK_DIRECCION_SUCURSAL NUMBER NOT NULL,
FK_TELEFONO_SUCURSAL NUMBER  NOT NULL,
CONSTRAINT FK_DIRECCION_SUCURSAL
FOREIGN KEY (FK_DIRECCION_SUCURSAL)
REFERENCES C##PROYECTO1.DIRECCION_SUCURSAL(ID_DIRECCION_SUCURSAL),

CONSTRAINT FK_TELEFONO_SUCURSAL
FOREIGN KEY (FK_TELEFONO_SUCURSAL)
REFERENCES C##PROYECTO1.TELEFONO_SUCURSAL(ID_TELEFONO_SUCURSAL)
);

/*TABLA CLIENTE*/
/*SE ELIGIO EL NOMBRE CLIENTE PARA ESTA TABLA POR QUE GUARDA LA INFORMACION DE CADA CLIENTE
 * CON ID_CLIENTE, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, EMAIL, FK_TELEFONO_CLIENTE Y FK_DIRECCION_CLIENTE
 * 
 * ID_CLIENTE: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA CADA CLIENTE,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * NOMBRE: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * APELLIDO_PATERNO: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * APELLIDO_MATERNO: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * EMAIL: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * FK_TELEFONO_CLIENTE: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA TELEFONO_CLIENTE
 * 
 * FK_DIRECCION_CLIENTE: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA DIRECCION_CLIENTE
 */
CREATE TABLE C##PROYECTO1.CLIENTE(
ID_CLIENTE NUMBER PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(100) NOT NULL,
APELLIDO_PATERNO VARCHAR2(100) NOT NULL,
APELLIDO_MATERNO VARCHAR2(100) NOT NULL,
EMAIL VARCHAR2(100) NOT NULL,
FK_TELEFONO_CLIENTE NUMBER NOT NULL,
FK_DIRECCION_CLIENTE NUMBER NOT NULL,
CONSTRAINT FK_TELEFONO_CLIENTE
FOREIGN KEY (FK_TELEFONO_CLIENTE)
REFERENCES C##PROYECTO1.TELEFONO_CLIENTE(ID_TELEFONO_CLIENTE),

CONSTRAINT FK_DIRECCION_CLIENTE
FOREIGN KEY (FK_DIRECCION_CLIENTE)
REFERENCES C##PROYECTO1.DIRECCION_CLIENTE(ID_DIRECCION_CLIENTE)
);

/*TABLA CAJA*/
/*SE ELIGIO EL NOMBRE CAJA PARA ESTA TABLA POR QUE GUARDA LA INFORMACION DE LAS COMPRAS QUE SE ALMACENAN EN LA CAJA DE LA SUCURSAL
 * CON ID_CAJA, NOMBRE, ESTATUS, FK_SUCURSAL
 * 
 * ID_CAJA: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA CADA CAJA,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * NOMBRE: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * ESTATUS: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * FK_SUCURSAL: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA SUCURSAL
 */
CREATE TABLE C##PROYECTO1.CAJA(
ID_CAJA NUMBER PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(100) NOT NULL,
ESTATUS VARCHAR2(100) NOT NULL,
FK_SUCURSAL NUMBER NOT NULL,
CONSTRAINT FK_SUCURSAL
FOREIGN KEY (FK_SUCURSAL)
REFERENCES C##PROYECTO1.SUCURSAL (ID_SUCURSAL)
);

/*TABLA PROVEEDOR*/
/* SE ELIGIO EL NOMBRE PROVEEDOR PARA ESTA TABLA POR QUE GUARDA LA INFORMACION DE CADA PROVEEDOR
 * CON ID_PROVEEDOR, NOMBRE, EMAIL, FK_TELEFONO_PROVEEDOR Y FK_DIRECCION_PROVEEDOR
 * 
 * ID_PROVEEDOR: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA CADA PROVEEDOR,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * NOMBRE: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * EMAIL: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * FK_TELEFONO_PROVEEDOR: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA TELEFONO_PROVEEDOR
 * 
 * FK_DIRECCION_PROVEEDOR: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA DIRECCION_PROVEEDOR
 */
CREATE TABLE C##PROYECTO1.PROVEEDOR(
ID_PROVEEDOR NUMBER PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(100) NOT NULL,
EMAIL VARCHAR2(100) NOT NULL,
FK_TELEFONO_PROVEEDOR NUMBER NOT NULL,
FK_DIRECCION_PROVEEDOR NUMBER NOT NULL,
CONSTRAINT FK_TELEFONO_PROVEEDOR
FOREIGN KEY (FK_TELEFONO_PROVEEDOR)
REFERENCES C##PROYECTO1.TELEFONO_PROVEEDOR (ID_TELEFONO_PROVEEDOR),

CONSTRAINT FK_DIRECCION_PROVEEDOR
FOREIGN KEY (FK_DIRECCION_PROVEEDOR)
REFERENCES C##PROYECTO1.DIRECCION_PROVEEDOR (ID_DIRECCION_PROVEEDOR)
);

/*TABLA PRODUCTO*/
/*SE ELIGIO EL NOMBRE PRODUCTO PARA ESTA TABLA POR QUE GUARDA LA INFORMACION DE CADA PRODUCTO
 * CON ID_PRODUCTO, NOMBRE, DESCRIPCION, STOCK, FK_CATEGORIA, FK_PROVEEDOR Y FK_IMPUESTO
 * 
 * ID_PRODUCTO: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA CADA PRODUCTO,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * NOMBRE: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * DESCRIPCION: SE ELEGIO VARCHAR2(200) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 200 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * STOCK: SE ELIGIO NUMBER POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * FK_CATEGORIA: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA CATEGORIA
 * 
 * FK_PROVEEDOR: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA PROVEEDOR
 * 
 * FK_IMPUESTO: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA IMPUESTO
 */
CREATE TABLE C##PROYECTO1.PRODUCTO(
ID_PRODUCTO NUMBER PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(100) NOT NULL,
DESCRIPCION VARCHAR2(200) NOT NULL,
STOCK NUMBER NOT NULL,
FK_CATEGORIA NUMBER NOT NULL,
FK_PROVEEDOR NUMBER NOT NULL,
FK_IMPUESTO NUMBER NOT NULL,
CONSTRAINT FK_CATEGORIA
FOREIGN KEY (FK_CATEGORIA)
REFERENCES C##PROYECTO1.CATEGORIA (ID_CATEGORIA),

CONSTRAINT FK_PROVEEDOR
FOREIGN KEY (FK_PROVEEDOR)
REFERENCES C##PROYECTO1.PROVEEDOR (ID_PROVEEDOR),

CONSTRAINT FK_IMPUESTO
FOREIGN KEY (FK_IMPUESTO)
REFERENCES C##PROYECTO1.IMPUESTO (ID_IMPUESTO)
);

/*TABLA PRECIO_HISTORICO*/
/*SE ELIGIO EL NOMBRE PRECIO_HISTORICO PARA ESTA TABLA POR QUE GUARDA LA INFORMACION DE LA TENDENCIA DEL MERCADO
 * CON ID_PRECIO_HISTORICO, PRECIO, FECHA_INICIO, FECHA_FIN Y FK_PRODUCTO
 * 
 * ID_PRECIO_HISTORICO: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA CADA PRECIO_HISTORICO,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * PRECIO: SE ELEGIO NUMBER POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * FECHA_INICIO: SE ELIGIO DATE POR QUE ES TIPO FECHA, EMPEZANDO POR AÑO, MES Y DIA.
 * 
 * FECHA_FIN: SE ELIGIO DATE POR QUE ES TIPO FECHA, EMPEZANDO POR AÑO, MES Y DIA.
 * 
 * FK_PRODUCTO: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA PRODUCTO
 */
CREATE TABLE C##PROYECTO1.PRECIO_HISTORICO(
ID_PRECIO_HISTORICO NUMBER PRIMARY KEY NOT NULL,
PRECIO FLOAT NOT NULL,
FECHA_INICIO DATE,
FECHA_FIN DATE,
FK_PRODUCTO NUMBER NOT NULL,
CONSTRAINT FK_PRODUCTO
FOREIGN KEY (FK_PRODUCTO)
REFERENCES C##PROYECTO1.PRODUCTO(ID_PRODUCTO)
);

/*TABLA PROMOCION*/
/*SE ELIGIO EL NOMBRE PROMOCION PARA ESTA TABLA POR QUE GUARDA LA INFORMACION DE LAS PROMOCIONES
 * CON ID_PROMOCION, NOMBRE, DESCRIPCION, FECHA_INICIO, FECHA_FIN, PORCENTAJE_DESCUENTO Y FK_PRODUCTO
 * 
 * ID_PROMOCION: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA CADA PROMOCION,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * NOMBRE: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * DESCRIPCION: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * FECHA_INICIO: SE ELIGIO DATE POR QUE ES TIPO FECHA, EMPEZANDO POR AÑO, MES Y DIA.
 * 
 * FECHA_FIN: SE ELIGIO DATE POR QUE ES TIPO FECHA, EMPEZANDO POR AÑO, MES Y DIA.
 * 
 * PORCENTAJE_DESCUENTO: SE ELIGIO NUMBER POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * FK_PRODUCTO: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA PRODUCTO
 * 
 */
CREATE TABLE C##PROYECTO1.PROMOCION(
ID_PROMOCION NUMBER PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(100) NOT NULL,
DESCRIPCION VARCHAR2(100) NOT NULL,
FECHA_INICIO DATE,
FECHA_FIN DATE,
PORCENTAJE_DESCUENTO FLOAT NOT NULL,
FK_PRODUCTO NUMBER NOT NULL,
CONSTRAINT FK_PRODUCTO_PROMOCION 
FOREIGN KEY (FK_PRODUCTO)
REFERENCES C##PROYECTO1.PRODUCTO(ID_PRODUCTO)
);

/*TABLA EMPLEADO*/
/*SE ELIGIO EL NOMBRE EMPLEADO PARA ESTA TABLA POR QUE GUARDA LA INFORMACION DE CADA EMPLEADO
 * CON ID_EMPLEADO, NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, EMAIL, FK_TELEFONO_EMPLEADO, FK_SUCURSAL Y FK_DIRECCION_EMPLEADO
 * 
 * ID_EMPLEADO: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA CADA EMPLEADO,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * NOMBRE: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * APELLIDO_PATERNO: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * APELLIDO_MATERNO: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * EMAIL: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * FK_TELEFONO_EMPLEADO: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA TELEFONO_EMPLEADO
 * 
 * FK_SUCURSAL: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA SUCURSAL
 * 
 * FK_DIRECCION_EMPLEADO: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA DIRECCION_EMPLEADO
 * */
CREATE TABLE C##PROYECTO1.EMPLEADO(
ID_EMPLEADO NUMBER PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(100) NOT NULL,
APELLIDO_PATERNO VARCHAR2(100) NOT NULL,
APELLIDO_MATERNO VARCHAR2(100) NOT NULL,
EMAIL VARCHAR2(100) NOT NULL,
FK_TELEFONO_EMPLEADO NUMBER NOT NULL,
FK_SUCURSAL NUMBER NOT NULL,
FK_DIRECCION_EMPLEADO NUMBER NOT NULL,
CONSTRAINT FK_TELEFONO_EMPLEADO
FOREIGN KEY (FK_TELEFONO_EMPLEADO)
REFERENCES C##PROYECTO1.TELEFONO_EMPLEADO (ID_TELEFONO_EMPLEADO),

CONSTRAINT FK_SUCURSAL_EMPLEADO
FOREIGN KEY (FK_SUCURSAL)
REFERENCES C##PROYECTO1.SUCURSAL (ID_SUCURSAL),

CONSTRAINT FK_DIRECCION_EMPLEADO
FOREIGN KEY (FK_DIRECCION_EMPLEADO)
REFERENCES C##PROYECTO1.DIRECCION_EMPLEADO (ID_DIRECCION_EMPLEADO)
);

/*TABLA USUARIO*/
/*SE ELIGIO EL NOMBRE USUARIO PARA ESTA TABLA POR QUE GUARDA LA INFORMACION DE LOS USUARIOS REGISTRADOS
 * CON ID_USUARIO, USERNAME, PASSWORD, EMAIL, ESTATUS, FK_ROL Y FK_EMPLEADO
 * 
 * ID_USUARIO: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA CADA USUARIO,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * USERNAME: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * PASSWORD: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * EMAIL: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA
 * 
 * ESTATUS: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA
 * 
 * FK_ROL: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA ROL
 * 
 * FK_EMPLEADO: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA EMPLEADO
 * 
 */
CREATE TABLE C##PROYECTO1.USUARIO(
ID_USUARIO NUMBER PRIMARY KEY NOT NULL,
USERNAME VARCHAR2(100) NOT NULL,
PASSWORD VARCHAR2(100) NOT NULL,
EMAIL VARCHAR2(100) NOT NULL,
ESTATUS VARCHAR2(100) NOT NULL,
FK_ROL NUMBER NOT NULL,
FK_EMPLEADO NUMBER NOT NULL,
CONSTRAINT FK_ROL
FOREIGN KEY (FK_ROL)
REFERENCES C##PROYECTO1.ROL(ID_ROL),

CONSTRAINT FK_EMPLEADO
FOREIGN KEY (FK_EMPLEADO)
REFERENCES C##PROYECTO1.EMPLEADO(ID_EMPLEADO)
);

/*TABLA COMPRA*/
/*SE ELIGIO EL NOMBRE COMPRA PARA ESTA TABLA POR QUE GUARDA LA INFORMACION DE CADA COMPRA REALIZADA
 * CON ID_COMPRA, FECHA, TOTAL, FK_EMPLEADO, FK_PROVEEDOR Y FK_SUCURSAL.
 * 
 * ID_COMPRA: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA CADA COMPRA,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * FECHA: SE ELIGIO DATE POR QUE ES TIPO FECHA, EMPEZANDO POR AÑO, MES Y DIA.
 * 
 * TOTAL: SE ELIGIO NUMBER POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * FK_EMPLEADO: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA EMPLEADO.
 * 
 * FK_PROVEEDOR: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA PROVEEDOR.
 * 
 * FK_SUCURSAL: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA SUCURSAL.
 * 
 */
CREATE TABLE C##PROYECTO1.COMPRA(
ID_COMPRA NUMBER PRIMARY KEY NOT NULL,
FECHA DATE,
TOTAL FLOAT NOT NULL,
FK_EMPLEADO NUMBER NOT NULL,
FK_PROVEEDOR NUMBER NOT NULL,
FK_SUCURSAL NUMBER NOT NULL,
CONSTRAINT FK_EMPLEADO_COMPRA
FOREIGN KEY (FK_EMPLEADO)
REFERENCES C##PROYECTO1.EMPLEADO (ID_EMPLEADO),

CONSTRAINT FK_PROVEEDOR_COMPRA
FOREIGN KEY (FK_PROVEEDOR)
REFERENCES C##PROYECTO1.PROVEEDOR (ID_PROVEEDOR),

CONSTRAINT FK_SUCURSAL_COMPRA
FOREIGN KEY (FK_SUCURSAL)
REFERENCES C##PROYECTO1.SUCURSAL (ID_SUCURSAL)
);

/*TABLA TURNO*/
/*SE ELIGIO EL NOMBRE TURNO PARA ESTA TABLA POR QUE GUARDA LA INFORMACION DE CADA TURNO
 * CON ID_TURNO,HORA_INICIO, HORA_FIN, FK_EMPLEADO Y FK_CAJA.
 * 
 * ID_TURNO: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA CADA TURNO,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * HORA_INICIO: SE ELIGIO DATE POR QUE ES TIPO FECHA Y HORA, EMPEZANDO POR AÑO, MES, DIA, HORA, MINUTOS Y SEGUNDOS
 * 
 * HORA_FIN: SE ELIGIO DATE POR QUE ES TIPO FECHA Y HORA, EMPEZANDO POR AÑO, MES, DIA, HORA, MINUTOS Y SEGUNDOS
 * 
 * FK_EMPLEADO: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA EMPLEADO.
 * 
 * FK_CAJA: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA CAJA.*/
CREATE TABLE C##PROYECTO1.TURNO(
ID_TURNO NUMBER PRIMARY KEY NOT NULL,
HORA_INICIO DATE,
HORA_FIN DATE,
FK_EMPLEADO NUMBER NOT NULL,
FK_CAJA NUMBER NOT NULL,
CONSTRAINT FK_EMPLEADO_TURNO
FOREIGN KEY (FK_EMPLEADO)
REFERENCES C##PROYECTO1.EMPLEADO (ID_EMPLEADO),

CONSTRAINT FK_CAJA
FOREIGN KEY (FK_CAJA)
REFERENCES C##PROYECTO1.CAJA (ID_CAJA)
);

/*TABLA DETALLES_DE_COMPRA*/ 
 /* SE ELIGIO EL NOMBRE DETALLES_DE_COMPRA PARA ESTA TABLA POR QUE GUARDA LA INFORMACION DE CADA DETALLE DE LA COMPRA
 * CON ID_DETALLE_DE_COMPRA, CANTIDAD, PRECIO_UNITARIO, FK_COMPRA, FK_PRODUCTO Y FK_METODO_DE_PAGO.
 * 
 * ID_DETALLES_DE_COMPRA: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA CADA DETALLE DE COMPRA,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * CANTIDAD: SE ELIGIO NUMBER POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * PRECIO_UNITARIO: SE ELIGIO NUMBER POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA
 * 
 * FK_COMPRA: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA COMPRA.
 * 
 * FK_PRODUCTO: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA PRODUCTO.
 * 
 * FK_METODO_DE_PAGO: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA METODO_DE_PAGO
 * */
CREATE TABLE C##PROYECTO1.DETALLES_DE_COMPRA(
ID_DETALLES_DE_COMPRA NUMBER PRIMARY KEY NOT NULL,
CANTIDAD NUMBER NOT NULL,
PRECIO_UNITARIO FLOAT NOT NULL,
FK_COMPRA NUMBER NOT NULL,
FK_PRODUCTO NUMBER NOT NULL,
FK_METODO_DE_PAGO NUMBER NOT NULL,
CONSTRAINT FK_COMPRA_DETALLE_DE_COMPRA
FOREIGN KEY (FK_COMPRA)
REFERENCES C##PROYECTO1.COMPRA (ID_COMPRA),

CONSTRAINT FK_PRODUCTO_DETALLE_DE_COMPRA
FOREIGN KEY (FK_PRODUCTO)
REFERENCES C##PROYECTO1.PRODUCTO (ID_PRODUCTO),

CONSTRAINT FK_METODO_DE_PAGO_DETALLE_COMPRAC
FOREIGN KEY (FK_METODO_DE_PAGO)
REFERENCES C##PROYECTO1.METODO_DE_PAGO (ID_METODO_DE_PAGO)
);

/*TABLA DE VENTA*/
 /*SE ELIGIO EL NOMBRE VENTA PARA ESTA TABLA POR QUE GUARDA LA INFORMACION DE CADA VENTA
 * CON ID_VENTA, FECHA, TOTAL, FK_CLIENTE, FK_EMPLEADO Y FK_CAJA.
 * 
 * ID_VENTA: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA CADA DETALLE DE VENTA,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * FECHA: SE ELIGIO DATE POR QUE ES TIPO FECHA, EMPEZANDO POR AÑO, MES Y DIA.
 * 
 * TOTAL: SE ELIGIO NUMBER POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA
 * 
 * FK_CLIENTE: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA CLIENTE.
 * 
 * FK_EMPLEADO: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA EMPLEADO.
 * 
 * FK_CAJA: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA CAJA 
 * 
 */
CREATE TABLE C##PROYECTO1.VENTA(
ID_VENTA NUMBER PRIMARY KEY NOT NULL,
FECHA DATE,
TOTAL FLOAT NOT NULL,
FK_CLIENTE NUMBER NOT NULL,
FK_EMPLEADO NUMBER NOT NULL,
FK_CAJA NUMBER NOT NULL,
CONSTRAINT FK_CLIENTE_VENTA
FOREIGN KEY (FK_CLIENTE)
REFERENCES C##PROYECTO1.CLIENTE (ID_CLIENTE),

CONSTRAINT FK_EMPLEADO_VENTA
FOREIGN KEY (FK_EMPLEADO)
REFERENCES C##PROYECTO1.EMPLEADO (ID_EMPLEADO),

CONSTRAINT FK_CAJA_VENTA
FOREIGN KEY (FK_CAJA)
REFERENCES C##PROYECTO1.CAJA (ID_CAJA)
 );

/*TABLA DETALLE_DE_VENTA*/
 /* SE ELIGIO EL NOMBRE DETALLE_DE_VENTA PARA ESTA TABLA POR QUE GUARDA LOS DETALLES DE CADA VENTA
 * CON ID_DETALLE_DE_VENTA, CANTIDAD, PRECIO_UNITARIO, DESCUENTO, FK_VENTA, FK_METODO_DE_PAGO, FK_PRODUCTO.
 * 
 * ID_DETALLE_DE_VENTA: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA CADA DETALLE DE VENTA,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * CANTIDAD: SE ELIGIO NUMBER POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA
 * 
 * PRECIO_UNITARIO: SE ELIGIO NUMBER POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA
 * 
 * DESCUENTO: SE ELIGIO NUMBER POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA
 * 
 * FK_VENTA: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA VENTA.
 * 
 * FK_METODO_DE_PAGO: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA METODO_DE_PAGO.
 * 
 * FK_PRODUCTO: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA PRODUCTO 
 */
CREATE TABLE C##PROYECTO1.DETALLE_DE_VENTA(
ID_DETALLE_DE_VENTA NUMBER PRIMARY KEY NOT NULL,
CANTIDAD NUMBER NOT NULL,
PRECIO_UNITARIO FLOAT NOT NULL,
DESCUENTO FLOAT NOT NULL,
FK_VENTA NUMBER NOT NULL,
FK_METODO_DE_PAGO NUMBER NOT NULL,
FK_PRODUCTO NUMBER NOT NULL,
CONSTRAINT FK_VENTA
FOREIGN KEY (FK_VENTA)
REFERENCES C##PROYECTO1.VENTA (ID_VENTA),

CONSTRAINT FK_METODO_DE_PAGO_DETALLE_VENTA
FOREIGN KEY (FK_METODO_DE_PAGO)
REFERENCES C##PROYECTO1.METODO_DE_PAGO (ID_METODO_DE_PAGO),

CONSTRAINT FK_PRODUCTO_DETALLE_VENTA
FOREIGN KEY (FK_PRODUCTO)
REFERENCES C##PROYECTO1.PRODUCTO (ID_PRODUCTO)
);

/*TABLA DE INVENTARIO_DE_MOVIMIENTOS*/
 /* SE ELIGIO EL NOMBRE INVENTARIO_DE_MOVIMIENTOS PARA ESTA TABLA POR QUE GUARDA LOS MOVIMIENTOS DEL INVENTARIO
 * CON ID_INVENTARIO_DE_MOVIMIENTOS, TIPO_MOVIMIENTO, CANTIDAD, FECHA, FK_PRODUCTO, FK_SUCURSAL, FK_DETALLE_DE_VENTA Y FK_DETALLES_DE_COMPRA.
 * 
 * ID_INVENTARIO_DE_MOVIMIENTOS: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA CADA MOVIMIENTO DEL INVENTARIO,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * TIPO_MOVIMIENTO: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * CANTIDAD: SE ELIGIO NUMBER POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA
 * 
 * FECHA: SE ELIGIO DATE POR QUE ES TIPO FECHA, EMPEZANDO POR AÑO, MES Y DIA.
 * 
 * FK_PRODUCTO: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA PRODUCTO.
 * 
 * FK_SUCURSAL: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA SUCURSAL.
 * 
 * FK_DETALLE_DE_VENTA: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA DETALLE_DE_VENTA
 * 
 * FK_DETALLES_DE_COMPRA: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA DETALLES_DE_COMPRA
 * 
 */
CREATE TABLE C##PROYECTO1.INVENTARIO_DE_MOVIMIENTOS(
ID_INVENTARIO_DE_MOVIMIENTOS NUMBER PRIMARY KEY NOT NULL,
TIPO_MOVIMIENTO VARCHAR2(100) NOT NULL,
CANTIDAD NUMBER NOT NULL,
FECHA DATE,
FK_PRODUCTO NUMBER NOT NULL,
FK_SUCURSAL NUMBER NOT NULL,
FK_DETALLE_DE_VENTA NUMBER NOT NULL,
FK_DETALLES_DE_COMPRA NUMBER NOT NULL,
CONSTRAINT FK_PRODUCTO_INVENTARIO_MOVIMIENTO
FOREIGN KEY (FK_PRODUCTO)
REFERENCES C##PROYECTO1.PRODUCTO (ID_PRODUCTO),

CONSTRAINT FK_SUCURSAL_INVENTARIO_MOVIMIENTOS
FOREIGN KEY (FK_SUCURSAL)
REFERENCES C##PROYECTO1.SUCURSAL (ID_SUCURSAL),

CONSTRAINT FK_DETALLE_DE_VENTA_INVENTARIO_MOVIMIENTO
FOREIGN KEY (FK_DETALLE_DE_VENTA)
REFERENCES C##PROYECTO1.DETALLE_DE_VENTA (ID_DETALLE_DE_VENTA),

CONSTRAINT FK_DETALLES_DE_COMPRA_INVENTARIO_MOVIMIENTO
FOREIGN KEY (FK_DETALLES_DE_COMPRA)
REFERENCES C##PROYECTO1.DETALLES_DE_COMPRA (ID_DETALLES_DE_COMPRA)
);

/*TABLA DE DEVOLUCIONES*/
 /* SE ELIGIO EL NOMBRE DEVOLUCIONES PARA ESTA TABLA POR QUE GUARDA LA INFORMACION DE CADA DEVOLUCION
 * CON ID_DEVOLUCIONES,FECHA , MOTIVO, FK_VENTA Y FK_EMPLEADO.
 * 
 * ID_DEVOLUCIONES: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA CADA DEVOLUCION,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * FECHA: SE ELIGIO DATE POR QUE ES TIPO FECHA Y HORA, EMPEZANDO POR AÑO, MES Y DIA.
 * 
 * MOTIVO: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * FK_VENTA: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA VENTA.
 * 
 * FK_EMPLEADO: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA EMPLEADO.
 */
CREATE TABLE C##PROYECTO1.DEVOLUCIONES(
ID_DEVOLUCIONES NUMBER PRIMARY KEY NOT NULL,
FECHA DATE,
MOTIVO VARCHAR2(100) NOT NULL,
FK_VENTA NUMBER NOT NULL,
FK_EMPLEADO NUMBER NOT NULL,
CONSTRAINT FK_VENTA_DEVOLUCIONES
FOREIGN KEY (FK_VENTA)
REFERENCES C##PROYECTO1.VENTA (ID_VENTA),

CONSTRAINT FK_EMPLEADO_DEVOLUCIONES
FOREIGN KEY (FK_EMPLEADO)
REFERENCES C##PROYECTO1.EMPLEADO (ID_EMPLEADO)
);

/*TABLA DE DETALLE_DEVOLUCION*/
 /* SE ELIGIO EL NOMBRE DETALLE_DEVOLUCION PARA ESTA TABLA POR QUE GUARDA LOS DETALLES DE CADA DEVOLUCION
 * CON ID_DETALLE_DEVOLUCION, CANTIDAD, MOTIVO, FK_DEVOLUCIONES Y FK_PRODUCTO.
 * 
 * ID_DETALLE_DEVOLUCION: SE ELEGIO NUMBER POR QUE NECESITA UN IDENTIFICADOR UNICO PARA CADA DETALLE DE LA DEVOLUCION,
 * ES LLAVE PRIMARIA DE ESTA TABLA, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * CANTIDAD: SE ELIGIO NUMBER POR QUE ES TIPO NUMERICO, NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * MOTIVO: SE ELEGIO VARCHAR2(100) POR QUE ES DE TIPO TEXTO, CON UNA LONGITUD DE 100 CARACTERES,
 * NO PUEDE QUEDARSE VACIA ESTA COLUMNA DE LA TABLA.
 * 
 * FK_DEVOLUCIONES: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA DEVOLUCIONES.
 * 
 * FK_PRODUCTO: SE ELIGIO NUMBER, ES IDENTIFICADOR UNICO Y ES LLAVE FORANEA DE LA TABLA PRODUCTO
 */
CREATE TABLE C##PROYECTO1.DETALLE_DEVOLUCION(
ID_DETALLE_DEVOLUCION NUMBER PRIMARY KEY NOT NULL,
CANTIDAD NUMBER NOT NULL,
MOTIVO VARCHAR2(100) NOT NULL,
FK_DEVOLUCIONES NUMBER NOT NULL,
FK_PRODUCTO NUMBER NOT NULL,
CONSTRAINT FK_DEVOLUCIONES
FOREIGN KEY (FK_DEVOLUCIONES)
REFERENCES C##PROYECTO1.DEVOLUCIONES (ID_DEVOLUCIONES),

CONSTRAINT FK_PRODUCTO_DETALLE_DEVOLUCION
FOREIGN KEY (FK_PRODUCTO)
REFERENCES C##PROYECTO1.PRODUCTO (ID_PRODUCTO)
);


